---
title: "Cash Grab Arena -- Playtest Data Analysis"
author: "Version 0.13.1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

# Load in relevant packages
library(ggplot2)
library(glue)
library(purrr)
library(tidyverse)
library(ggforce)

#Write functions to append the data more efficiently.
read_in_data <- function(fileName, playtestDate = "99/99/9999", playtestVersion = "0.0.*", hasHeaders = FALSE) {
  out <- read.csv(fileName, hasHeaders)
  colnames(out) <- c("ID", "Class", "Trinket", "Map", "Game_ID", "Kills", "Coins", "Is_Complete")
  out <- out |>
    mutate(Date = playtestDate,
           Version = playtestVersion)
  return(out)
}

merge_playtests <- function(dataframes) {
  out <- dataframes[[1]]
  
  for (i in 2:length(dataframes)) {
    out <- rbind(out, dataframes[[i]])
  }
  
  return(out)
}

generate_seqID <- function(x) {
  
  x |>
    group_by(Game_ID) |>
    mutate(seqID = 1:n())
  
}
```

```{r echo=FALSE}
# Read in data
setwd("data")
test1 <- read_in_data("test_data.csv", "01/01/2025", "0.13.1", TRUE)
test2 <- read_in_data("test_data2.csv", "02/02/2025", "0.13.1", TRUE)


#Merge obs. into one set of data
dflist <- list(test1, test2)
cgada <- merge_playtests(dflist)
cgada <- generate_seqID(cgada)
```

# Class Data

## General Class Popularity

```{r echo=FALSE}
suppressMessages(
  cgada |>
  group_by(Class, Date) |>
  summarise(n=n()) |>
  ungroup() |> group_by(Class) |>
  summarise(sd = sd(n),
            sum = sum(n)) |>
  ggplot(aes(x = Class, y = sum)) +
  geom_bar(stat = "identity", color = "black", fill = "green") +
  theme(legend.position = "none") +
  xlab("Class") + ylab("Number of Lives Played") +
  labs(title = "Class Popularity (% of Total Lives Played)",
       caption = "Red line indicates expected popularity assuming classes are to be equally used.
                  Error bars indicate values which we could likely observe if we repeated a sample of the same number of playtests.") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_errorbar(aes(ymin = sum - sd,
                ymax = sum + sd),
                width = 0.5) +
  geom_hline(yintercept = nrow(cgada) / nrow(distinct(cgada, Class)), color = "red")
)

```

## Kills Per Entry

```{r echo=FALSE}
suppressMessages(
  cgada |>
  group_by(Class) |>
  summarise(Entry = n(),
         KPE = sum(Kills) / sum(Entry),
         sd = sd(Kills),
         se = sd / sqrt(Entry)) |>
  ggplot(aes(x = Class, y = KPE)) +
  geom_bar(stat = "identity", color = "black", fill = "slateblue") +
  theme(legend.position = "none") +
  xlab("Class") + ylab("Kills") +
  labs(title = "Class Kills per Entry",
       caption = "Red line indicates the average Kills per Entry across all classes.
                  Error bars indicate values which we could likely observe on repeated playtests, accounting for sample size.") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_errorbar(aes(ymin = KPE - se,
                ymax = KPE + se),
                width = 0.5) +
  geom_hline(yintercept = sum(cgada$Kills) / nrow(cgada), color = "red")
)
```

## Coins Per Entry

```{r echo=FALSE}
suppressMessages(
  cgada |>
  group_by(Class) |>
  summarise(Entry = n(),
         CPE = sum(Coins) / sum(Entry),
         sd = sd(Coins),
         se = sd / sqrt(Entry)) |>
  ggplot(aes(x = Class, y = CPE)) +
  geom_bar(stat = "identity", color = "black", fill = "gold") +
  theme(legend.position = "none") +
  xlab("Class") + ylab("Coins") +
  labs(title = "Class Coins per Entry",
       caption = "Red line indicates the average Coins per Entry across all classes.
                  Error bars indicate values which we could likely observe on repeated playtests, accounting for sample size.") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_errorbar(aes(ymin = CPE - se,
                ymax = CPE + se),
                width = 0.5) +
  geom_hline(yintercept = sum(cgada$Coins) / nrow(cgada), color = "red")
)
```

## Relative Efficiency

```{r echo=FALSE}
suppressMessages(
  cgada |>
  group_by(Class) |>
  summarise(Entry = n(),
         KPE = sum(Kills) / sum(Entry),
         CPE = sum(Coins) / sum(Entry)) |>
  mutate(KPE.scaled = (KPE - (0.8 * min(KPE))) / ((1.2 * max(KPE)) - (0.8 * min(KPE))),
         CPE.scaled = (CPE - (0.8 * min(CPE))) / ((1.2 * max(CPE)) - (0.8 * min(CPE))),
         Rel.Eff = KPE.scaled - CPE.scaled) |>
  ggplot(aes(x = Class, y = Rel.Eff)) +
  geom_bar(stat = "identity", color = "black", fill = "red") +
  theme(legend.position = "none") +
  xlab("Class") + ylab("% Difference") +
  labs(title = "Relative Efficiency",
       caption = "Positive values indicate more efficient kill generation per life.
          Negative values indicate more efficient coin earnings per life.
          Larger magnitudes suggest more extreme specializations.") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_hline(yintercept = 0, color = "black")
)
```

## Trinket Popularity

```{r echo=FALSE}

suppressMessages(
  cgada |>
  group_by(Trinket, Date) |>
  summarise(n=n()) |>
  ungroup() |> group_by(Trinket) |>
  summarise(sd = sd(n),
            sum = sum(n)) |>
  ggplot(aes(x = Trinket, y = sum)) +
  geom_bar(stat = "identity", color = "black", fill = "orange") +
  theme(legend.position = "none") +
  xlab("Trinket") + ylab("Number of Lives Played") +
  labs(title = "Trinket Popularity",
       caption = "Red line indicates expected popularity assuming classes are to be equally used.
                  Error bars indicate values which we could likely observe if we repeated a sample of the same number of playtests.") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_errorbar(aes(ymin = sum - sd,
                ymax = sum + sd),
                width = 0.5) +
  geom_hline(yintercept = nrow(cgada) / nrow(distinct(cgada, Trinket)), color = "red")
)
```

## Trinket Efficacy

```{r echo=FALSE}
suppressMessages(
  cgada |>
  group_by(Trinket) |>
  summarise(Entry = n(),
         KPE = sum(Kills) / sum(Entry),
         sd = sd(Kills),
         se = sd / sqrt(Entry)) |>
  ggplot(aes(x = Trinket, y = KPE)) +
  geom_bar(stat = "identity", color = "black", fill = "royalblue") +
  theme(legend.position = "none") +
  xlab("Trinket") + ylab("Kills") +
  labs(title = "Trinket Kills per Entry",
       caption = "Red line indicates the average Kills per Entry across all classes.
                  Error bars indicate values which we could likely observe on repeated playtests, accounting for sample size.") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_errorbar(aes(ymin = KPE - se,
                ymax = KPE + se),
                width = 0.5) +
  geom_hline(yintercept = sum(cgada$Kills) / nrow(cgada), color = "red")
)
```
```{r echo=FALSE}
suppressMessages(
  cgada |>
  group_by(Trinket) |>
  summarise(Entry = n(),
         CPE = sum(Coins) / sum(Entry),
         sd = sd(Coins),
         se = sd / sqrt(Entry)) |>
  ggplot(aes(x = Trinket, y = CPE)) +
  geom_bar(stat = "identity", color = "black", fill = "gold3") +
  theme(legend.position = "none") +
  xlab("Trinket") + ylab("Coins") +
  labs(title = "Trinket Coins per Entry",
       caption = "Red line indicates the average Coins per Entry across all classes.
                  Error bars indicate values which we could likely observe on repeated playtests, accounting for sample size.") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_errorbar(aes(ymin = CPE - se,
                ymax = CPE + se),
                width = 0.5) +
  geom_hline(yintercept = sum(cgada$Coins) / nrow(cgada), color = "red")
)
```

## Map Data [WIP]

## Within-Game Data [WIP]

## Some Fun Tidbits

### Top Class-and-Trinket Combos by Lives Played

```{r echo=FALSE}
suppressMessages(
print(
cgada |>
  group_by(Class, Trinket) |>
  summarise(LivesPlayed = n()) |>
  arrange(desc(LivesPlayed)),
n = 20)
)
```

### Most Coins Generated on an Entry

```{r echo=FALSE}
cgada |>
  arrange(desc(Coins)) |>
  select(Class, Trinket, Map, Coins) |>
  slice_head(n = 10)
```

### Most Kills on an Entry

```{r echo=FALSE}
cgada |>
  arrange(desc(Kills)) |>
  select(Class, Trinket, Map, Kills) |>
  slice_head(n = 10)
```

[Click here to return to the main page.](https://maxscampbell.github.io/cgada/)